### ISSUE TITLE
SQL Entries missing

### ISSUE THREAD

**Issue by gree303** [pyroAdrian/ProductLicense#1]
Hello Adrian,
thanks for this great extension.
Somehow the SQL table entries are missing.
Could you please upload the table structure?
Simple SQL export from your DB would be just enough.
Thanks ahead.
Best greetings

**Comment by pyroAdrian** [comment]
Hi @gree303,

I've just added the missing sql files. The issue was the the sql files were ignored in .gitignore file.
Thank you for reporting and let me know if you find any bugs.

Regards,
Adrian

**Comment by gree303** [comment]
Hello Adrian, 
thanks for adding the sql files.

I've tried to install the package with Connect Package Manager.
It reports the following Error (CE 1.8)

CONNECT ERROR: Package file is invalid
Invalid package name, allowed: [a-zA-Z0-9_-] chars
Invalid version, should be like: x.x.x
Invalid stability
Invalid date, should be YYYY-DD-MM
Invalid channel URL
Empty authors section
Empty package contents section

Do you mind adding these information to the package?
I've tried installing it by copying it manually. But then the SQL entries are not getting applied to the DB for no reason - not sure if the files are "self-installing" by just copying them...

Any work around will also do the job. Haven't found one up to now ;/

Thanks for your great support.

**Comment by pyroAdrian** [comment]
Hi @gree303,

The extension is in development phase and you can't use the package manager until the 1.0 version. Until the tag 1.0 you can manually apply the files in community code poll.

Regarding the issue, the SQL files are working but initially you've installed the extension without the SQL files and magento will not try to run them again.

The quick solution is to run this SQL : 
DELETE FROM core_resource where code like '%pyro_licenses%';

Regards,
Adrian
